CLOUDP-113388: E2E Test Coverage - Operator Install with OLM on Openshift (#2859)

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -11,14 +11,15 @@ fi
 
 mkdir -p "$(go env GOPATH)/bin"
 
+# Generates a yaml file to install the operator from the helm sources.
 function generate_standalone_yaml() {
-    # Generates a yaml file to install the operator from the helm sources.
+    HELM_OPTS=$@
 
     charttmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'charttmpdir')
     charttmpdir=${charttmpdir}/chart
     mkdir -p "${charttmpdir}"
 
-    helm template --namespace mongodb -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}"
+    helm template --namespace mongodb -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}" ${HELM_OPTS[@]}
 
     cat "${charttmpdir}/enterprise-operator/templates/"{operator-roles.yaml,database-roles.yaml,operator.yaml} > public/mongodb-enterprise.yaml
 
@@ -26,7 +27,7 @@ function generate_standalone_yaml() {
 
     rm -rf "${charttmpdir:?}/*"
 
-    helm template --namespace mongodb -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}" --values helm_chart/values-openshift.yaml
+    helm template --namespace mongodb -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}" --values helm_chart/values-openshift.yaml ${HELM_OPTS[@]}
 
     cat "${charttmpdir}/enterprise-operator/templates/"{operator-roles.yaml,database-roles.yaml,operator.yaml} > public/mongodb-enterprise-openshift.yaml
 }
@@ -65,57 +66,70 @@ function update_values_yaml_files() {
     git add go.sum
 }
 
-# We need to generate the values files first
-update_values_yaml_files
-# The values files are used for generating the standalone yaml
-generate_standalone_yaml
+function pre_commit() {
+  # We need to generate the values files first
+  update_values_yaml_files
+  # The values files are used for generating the standalone yaml
+  generate_standalone_yaml
 
-black_formatting
+  black_formatting
 
-source scripts/evergreen/lint_code.sh
+  source scripts/evergreen/lint_code.sh
 
-if echo "$git_last_changed" | grep -q 'go.mod'; then
-  echo 'regenerating licenses.csv'
-  source scripts/evergreen/update_licenses.sh
-  git add licenses.csv
+  if echo "$git_last_changed" | grep -q 'go.mod'; then
+    echo 'regenerating licenses.csv'
+    source scripts/evergreen/update_licenses.sh
+    git add licenses.csv
+  fi
+
+  if echo "$git_last_changed" | grep -q 'public/tools/multicluster'; then
+    echo 'regenerating multicluster RBAC public example'
+    pushd public/tools/multicluster
+    EXPORT_RBAC_SAMPLES="true" go test -run TestPrintingOutRolesServiceAccountsAndRoleBindings
+    popd
+    git add public/samples/multi-cluster-cli-gitops
+  fi
+
+  if find . -name "Makefile"|grep -v vendor|xargs grep "\${"
+  then
+      echo 'ERROR: Makefiles should NEVER contain curly brackets variables'
+      exit 1
+  fi
+
+  # Makes sure there are not erroneous kubebuilder annotations that can
+  # end up in CRDs as descriptions.
+  if grep "// kubebuilder" ./* -r --exclude-dir=vendor --include=\*.go ; then
+      echo "Found an erroneous kubebuilder annotation"
+      exit 1
+  fi
+
+  # run shellcheck on all modified shell scripts
+  for file in $(echo "$git_last_changed" | grep -v '\.go$' | grep -v '\.py' | grep -v '\.yaml' | grep -v '\.json')
+  do
+      # check if bash script
+      if head -1 "${file}" | grep "#!/usr/bin/env bash" > /dev/null
+      then
+          # see https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
+          if ! grep "set -Eeou pipefail" "${file}" > /dev/null
+          then
+              echo "set opts not set on ${file}"
+              exit 1
+          fi
+          if ! shellcheck -x "${file}"; then
+              echo "shellcheck failed on ${file}"
+              exit 1
+          fi
+      fi
+  done
+}
+
+cmd=${1:-"pre-commit"}
+
+if [[ "${cmd}" == "generate_standalone_yaml" ]]; then
+  shift 1
+  generate_standalone_yaml "$@"
+elif [[ "${cmd}" == "pre-commit" ]]; then
+  pre_commit
 fi
 
-if echo "$git_last_changed" | grep -q 'public/tools/multicluster'; then
-  echo 'regenerating multicluster RBAC public example'
-  pushd public/tools/multicluster
-  EXPORT_RBAC_SAMPLES="true" go test -run TestPrintingOutRolesServiceAccountsAndRoleBindings
-  popd
-  git add public/samples/multi-cluster-cli-gitops
-fi
 
-if find . -name "Makefile"|grep -v vendor|xargs grep "\${"
-then
-    echo 'ERROR: Makefiles should NEVER contain curly brackets variables'
-    exit 1
-fi
-
-# Makes sure there are not erroneous kubebuilder annotations that can
-# end up in CRDs as descriptions.
-if grep "// kubebuilder" ./* -r --exclude-dir=vendor --include=\*.go ; then
-    echo "Found an erroneous kubebuilder annotation"
-    exit 1
-fi
-
-# run shellcheck on all modified shell scripts
-for file in $(echo "$git_last_changed" | grep -v '\.go$' | grep -v '\.py' | grep -v '\.yaml' | grep -v '\.json')
-do
-    # check if bash script
-    if head -1 "${file}" | grep "#!/usr/bin/env bash" > /dev/null
-    then
-        # see https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
-        if ! grep "set -Eeou pipefail" "${file}" > /dev/null
-        then
-            echo "set opts not set on ${file}"
-            exit 1
-        fi
-        if ! shellcheck -x "${file}"; then
-            echo "shellcheck failed on ${file}"
-            exit 1
-        fi
-    fi
-done
