CLOUDP-295444 - add proxy support for the operator (#4044)
# Summary

This patchs adds the following:
- [x] proxy env var on the container the operator deploys can be
propagated to the agent.
This is sufficient because both the operator and the agent take the
proxy environment variables into account.
- [x] Propagating the proxy environment variables is protected by the
`PROPAGATE_PROXY_ENV` environment variable.
This is necessary because it's valid to not propagate proxy environment
variables in a multi-cluster context by default.
- [x] e2e test with squid-proxy.
I used squid-proxy because of the availability of an image published by
a certified publisher. Nginx or writing a proxy from scratch is not
ideal for a generic forward proxy.

## Proof of Work

Successful EVG run:
https://spruce.mongodb.com/version/67a27126d70b050007296e75

## Checklist
- [x] Have you linked a jira ticket and/or is the ticket in the title?
- [x] Have you checked whether your jira ticket required DOCSP changes?
- [x] Have you checked for release_note changes?

---------

Co-authored-by: Mircea Cosbuc <mircea.cosbuc@mongodb.com>

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -4,7 +4,7 @@ set -Eeou pipefail
 
 source scripts/dev/set_env_context.sh
 if [ -f "${workdir}"/venv/bin/activate ]; then
-    source "${workdir}"/venv/bin/activate
+  source "${workdir}"/venv/bin/activate
 fi
 
 if [[ -z "${EVERGREEN_MODE:-}" ]]; then
@@ -44,7 +44,7 @@ function generate_standalone_yaml() {
   # generate openshift files for kustomize used for generating OLM bundle
   rm -rf "${charttmpdir:?}/*"
   helm template --namespace mongodb -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}" --values helm_chart/values-openshift.yaml \
-   --set operator.webhook.registerConfiguration=false --set operator.webhook.installClusterRole=false ${HELM_OPTS[@]}
+    --set operator.webhook.registerConfiguration=false --set operator.webhook.installClusterRole=false ${HELM_OPTS[@]}
 
   # update kustomize files for OLM bundle with files generated for openshift
   cp "${charttmpdir}/enterprise-operator/templates/operator.yaml" config/manager/manager.yaml
@@ -60,7 +60,7 @@ function generate_standalone_yaml() {
 
 function python_formatting() {
   # installing Black
-  if ! command -v "black" >/dev/null ; then
+  if ! command -v "black" >/dev/null; then
     pip install -r requirements.txt
   fi
 
@@ -138,8 +138,8 @@ run_shellcheck() {
   local file="$1"
   echo "Running shellcheck on $file"
   if ! shellcheck -x "$file" -e SC2154 -e SC1091 -e SC1090 -o require-variable-braces -P "scripts"; then
-     echo "shellcheck failed on $file"
-     exit 1
+    echo "shellcheck failed on $file"
+    exit 1
   fi
 }
 
@@ -155,7 +155,7 @@ start_shellcheck() {
 
   # Wait for all background jobs
   for job in $(jobs -p); do
-      wait "$job" || exit 1
+    wait "$job" || exit 1
   done
 
 }
