Fix community operator reference in go.mod (#2896)

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -13,78 +13,75 @@ mkdir -p "$(go env GOPATH)/bin"
 
 # Generates a yaml file to install the operator from the helm sources.
 function generate_standalone_yaml() {
-    HELM_OPTS=$@
+  HELM_OPTS=$@
 
-    charttmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'charttmpdir')
-    charttmpdir=${charttmpdir}/chart
-    mkdir -p "${charttmpdir}"
+  charttmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'charttmpdir')
+  charttmpdir=${charttmpdir}/chart
+  mkdir -p "${charttmpdir}"
 
-    helm template --namespace mongodb -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}" ${HELM_OPTS[@]}
+  helm template --namespace mongodb -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}" ${HELM_OPTS[@]}
 
-    cat "${charttmpdir}/enterprise-operator/templates/"{operator-roles.yaml,database-roles.yaml,operator.yaml} > public/mongodb-enterprise.yaml
+  cat "${charttmpdir}/enterprise-operator/templates/"{operator-roles.yaml,database-roles.yaml,operator.yaml} >public/mongodb-enterprise.yaml
 
-    cat "helm_chart/crds/"* > public/crds.yaml
+  cat "helm_chart/crds/"* >public/crds.yaml
 
-    rm -rf "${charttmpdir:?}/*"
+  rm -rf "${charttmpdir:?}/*"
 
-    helm template --namespace mongodb -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}" --values helm_chart/values-openshift.yaml ${HELM_OPTS[@]}
+  helm template --namespace mongodb -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}" --values helm_chart/values-openshift.yaml ${HELM_OPTS[@]}
 
-    cat "${charttmpdir}/enterprise-operator/templates/"{operator-roles.yaml,database-roles.yaml,operator.yaml} > public/mongodb-enterprise-openshift.yaml
+  cat "${charttmpdir}/enterprise-operator/templates/"{operator-roles.yaml,database-roles.yaml,operator.yaml} >public/mongodb-enterprise-openshift.yaml
 }
 
+function black_formatting() {
+  # installing Black
+  if ! command -v "black" >/dev/null; then
+    pip3 install -r docker/mongodb-enterprise-tests/requirements-dev.txt
+  fi
 
-function black_formatting()
-{
-    # installing Black
-    if ! command -v "black" > /dev/null; then
-        pip3 install -r docker/mongodb-enterprise-tests/requirements-dev.txt
-    fi
-
-    # Black formatting of every python file that was changed
-    for file in $( echo "$git_last_changed" | grep '\.py$')
-    do
-        black -q "$file"
-        git add "$file"
-    done
+  # Black formatting of every python file that was changed
+  for file in $(echo "$git_last_changed" | grep '\.py$'); do
+    black -q "$file"
+    git add "$file"
+  done
 }
 
 function update_values_yaml_files() {
-    # ensure that all helm values files are up to date.
-    # shellcheck disable=SC2154
-    if [[ -z "${workdir:-}" ]]; then
-      scripts/evergreen/release/update_helm_values_files.py
-    else
-      "${workdir}"/venv/bin/python scripts/evergreen/release/update_helm_values_files.py
-    fi
+  # ensure that all helm values files are up to date.
+  # shellcheck disable=SC2154
+  if [[ -z "${workdir:-}" ]]; then
+    scripts/evergreen/release/update_helm_values_files.py
+  else
+    "${workdir}"/venv/bin/python scripts/evergreen/release/update_helm_values_files.py
+  fi
 
-    # commit any changes we made
-    git add helm_chart/values.yaml
-    git add helm_chart/values-openshift.yaml
+  # commit any changes we made
+  git add helm_chart/values.yaml
+  git add helm_chart/values-openshift.yaml
 
-    # these can change if the version of community operator is different
-    git add go.mod
-    git add go.sum
+  # these can change if the version of community operator is different
+  git add go.mod
+  git add go.sum
 }
 
 function update_release_json() {
-    # ensure that release.json is up 2 date
-    # shellcheck disable=SC2154
-    if [[ -z "${workdir:-}" ]]; then
-      scripts/evergreen/release/update_release.py
-    else
-      "${workdir}"/venv/bin/python scripts/evergreen/release/update_release.py
-    fi
+  # ensure that release.json is up 2 date
+  # shellcheck disable=SC2154
+  if [[ -z "${workdir:-}" ]]; then
+    scripts/evergreen/release/update_release.py
+  else
+    "${workdir}"/venv/bin/python scripts/evergreen/release/update_release.py
+  fi
 
-    # commit any changes we made
-    git add release.json
+  # commit any changes we made
+  git add release.json
 }
 
 function update_community_operator_dependency() {
-     go get github.com/mongodb/mongodb-kubernetes-operator@master
+  go get github.com/mongodb/mongodb-kubernetes-operator@master
 
-     # these can change if the version of community operator is different
-     git add go.mod
-     git add go.sum
+  # these can change if the version of community operator is different
+  git add go.mod
+  git add go.sum
 }
 
 function pre_commit() {
@@ -103,7 +100,7 @@ function pre_commit() {
 
   if echo "$git_last_changed" | grep -q 'go.mod'; then
     echo 'regenerating licenses.csv'
-    source scripts/evergreen/update_licenses.sh
+    scripts/evergreen/update_licenses.sh
     git add licenses.csv
   fi
 
@@ -115,36 +112,32 @@ function pre_commit() {
     git add public/samples/multi-cluster-cli-gitops
   fi
 
-  if find . -name "Makefile"|grep -v vendor|xargs grep "\${"
-  then
-      echo 'ERROR: Makefiles should NEVER contain curly brackets variables'
-      exit 1
+  if find . -name "Makefile" | grep -v vendor | xargs grep "\${"; then
+    echo 'ERROR: Makefiles should NEVER contain curly brackets variables'
+    exit 1
   fi
 
   # Makes sure there are not erroneous kubebuilder annotations that can
   # end up in CRDs as descriptions.
-  if grep "// kubebuilder" ./* -r --exclude-dir=vendor --include=\*.go ; then
-      echo "Found an erroneous kubebuilder annotation"
-      exit 1
+  if grep "// kubebuilder" ./* -r --exclude-dir=vendor --include=\*.go; then
+    echo "Found an erroneous kubebuilder annotation"
+    exit 1
   fi
 
   # run shellcheck on all modified shell scripts
-  for file in $(echo "$git_last_changed" | grep -v '\.go$' | grep -v '\.py' | grep -v '\.yaml' | grep -v '\.json')
-  do
-      # check if bash script
-      if head -1 "${file}" | grep "#!/usr/bin/env bash" > /dev/null
-      then
-          # see https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
-          if ! grep "set -Eeou pipefail" "${file}" > /dev/null
-          then
-              echo "set opts not set on ${file}"
-              exit 1
-          fi
-          if ! shellcheck -x "${file}"; then
-              echo "shellcheck failed on ${file}"
-              exit 1
-          fi
+  for file in $(echo "$git_last_changed" | grep -v '\.go$' | grep -v '\.py' | grep -v '\.yaml' | grep -v '\.json'); do
+    # check if bash script
+    if head -1 "${file}" | grep "#!/usr/bin/env bash" >/dev/null; then
+      # see https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
+      if ! grep "set -Eeou pipefail" "${file}" >/dev/null; then
+        echo "set opts not set on ${file}"
+        exit 1
       fi
+      if ! shellcheck -x "${file}"; then
+        echo "shellcheck failed on ${file}"
+        exit 1
+      fi
+    fi
   done
 }
 
@@ -156,5 +149,3 @@ if [[ "${cmd}" == "generate_standalone_yaml" ]]; then
 elif [[ "${cmd}" == "pre-commit" ]]; then
   pre_commit
 fi
-
-
