CLOUDP-279913 CLOUDP-279247 CLOUDP-279917 CLOUDP-279918 CLOUDP-279919 CLOUDP-283266 Multi Cluster Sharded Non-Service Mesh (#3862)
# Summary

This Pull Request introduces the Multi Cluster Sharded support with No
Services Mesh.

Other notable enhancements:

* Fixed Single Cluster Placeholder replacements
* Added additional debugging information for Agent registration (useful
for this scenario)
* Unified Service Creation

## Documentation changes

* [x] Add an entry to [release notes](.../RELEASE_NOTES.md).
* [x] When needed, make sure you create a new [DOCSP
ticket](https://jira.mongodb.org/projects/DOCSP) that documents your
change.

## Changes to CRDs

* [x] Add `slaskawi`(Sebastian) and `@giohan` (George) as reviewers.
* [x] Make sure any changes are reflected on `/public/samples`
directory.

---------

Co-authored-by: Nam Nguyen <nam.nguyen@mongodb.com>
Co-authored-by: Julien-Ben <33035980+Julien-Ben@users.noreply.github.com>
Co-authored-by: Dan Mckean <44909130+dan-mckean@users.noreply.github.com>

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -132,14 +132,18 @@ function pre_commit() {
   fi
 
   # run shellcheck on all modified shell scripts
-  for file in $(echo "$git_last_changed" | grep -v '\.go$' | grep -v '\.py' | grep -v '\.yaml' | grep -v '\.json'); do
-    # check if bash script
-    if head -1 "${file}" | grep "#!/usr/bin/env bash" >/dev/null; then
-      if ! shellcheck -x "${file}" -e SC2154 -e SC1091 -P "$(dirname "${file}")"; then
-        echo "shellcheck failed on ${file}"
-        exit 1
+  for file in $git_last_changed; do
+    if [[ $file =~ \.go$ || $file =~ \.py$ || $file =~ \.yaml$ || $file =~ \.json$ ]]; then
+      # check if bash script
+      if head -1 "${file}" | grep "#!/usr/bin/env bash" >/dev/null; then
+        echo "Running spellcheck on $file"
+        if ! shellcheck -x "${file}" -e SC2154 -e SC1091 -P "$(dirname "${file}")"; then
+          echo "shellcheck failed on ${file}"
+          exit 1
+        fi
       fi
     fi
+
   done
 }
 
