fix shellcheck and add linting for curly brackets (#4027)
# Summary

Fixed a bug where shellcheck didn't check any bash script.
Modified shellcheck to verify if there are curly brackets around
variables in our bash scripts, to ensure consistency.
Shellcheck will now run on every script, not just on modified files.

## Proof of work
* shellcheck logs here:
https://evergreen.mongodb.com/task/ops_manager_kubernetes_go_unit_tests_lint_repo_patch_694d8d0898c130292050a020ce03d0ea3d643637_678a64e181fc830007438e83_25_01_17_14_10_43
* shellcheck failing here:
https://spruce.mongodb.com/task/ops_manager_kubernetes_go_unit_tests_lint_repo_patch_694d8d0898c130292050a020ce03d0ea3d643637_678a2ad07fac740007004260_25_01_17_10_02_57/logs?execution=4

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -130,15 +130,13 @@ function pre_commit() {
   fi
 
   # run shellcheck on all modified shell scripts
-  for file in $git_last_changed; do
-    if [[ $file =~ \.go$ || $file =~ \.py$ || $file =~ \.yaml$ || $file =~ \.json$ ]]; then
-      # check if bash script
-      if head -1 "${file}" | grep "#!/usr/bin/env bash" >/dev/null; then
-        echo "Running spellcheck on $file"
-        if ! shellcheck -x "${file}" -e SC2154 -e SC1091 -P "$(dirname "${file}")"; then
-          echo "shellcheck failed on ${file}"
-          exit 1
-        fi
+  for file in $(find ./scripts -type f -not -name "*.sh") $(find . -type f -name "*.sh"); do
+    # check if bash script
+    if head -1 "${file}" | grep "#!/usr/bin/env bash" >/dev/null; then
+      echo "Running shellcheck on ${file}"
+      if ! shellcheck -x "${file}" -e SC2154 -e SC1091 -o require-variable-braces -P "$(dirname "${file}")"; then
+        echo "shellcheck failed on ${file}"
+        exit 1
       fi
     fi
 
