CLOUDP-46342: Update OM versions in Evergreen file (#317)

diff --git a/.evergreen.yml b/.evergreen.yml
--- a/.evergreen.yml
+++ b/.evergreen.yml
@@ -6,13 +6,13 @@ stepback: true
 exec_timeout_secs: 1800 # 30 minutes is the longest we'll ever run
 variables:
   - &ops_manager_40_first
-    ops_manager_version: "4.0.5.50245.20181031T0042Z-1_test"
+    ops_manager_version: "4.0.11.50485.20190502T1847Z-1_test"
     ops_manager_namespace: "operator-testing-40-first"
     node_port: 30041
-  - &ops_manager_40_current
-    ops_manager_version: "4.0.12.50517.20190605T1533Z-1_test"
-    ops_manager_namespace: "operator-testing-40-current"
-    node_port: 30040
+  - &ops_manager_42_current
+    ops_manager_version: "4.2.0.56423.20190722T1139Z-1_test"
+    ops_manager_namespace: "operator-testing-42-current"
+    node_port: 30043
 
 # TODO: CLOUDP-42158 there are some incompatibilities with the operator and 4.1.x Ops Managers
 #  - &ops_manager_41_current
@@ -31,6 +31,14 @@ variables:
     prebuilt_operator_name: mdb-operator
     prebuilt_registry: quay.io/some
     prebuilt_images_run: true
+
+    # Openshift v3.11 Testing Environment
+  - &kubernetes_environment_openshift_3_11:
+    kube_environment_name: openshift_3_11
+
+    # Kops Vanilla Kubernetes v1.11
+  - &kubernetes_environment_vanilla_1_11:
+    kube_environment_name: vanilla_1_11
 
 functions:
   "golint":
@@ -168,7 +176,7 @@ functions:
         script: |
             src/github.com/10gen/ops-manager-kubernetes/scripts/evergreen/setup_docker
 
-  "setup_kubectl":
+  download_kubectl:
     - command: shell.exec
       params:
         shell: bash
@@ -176,33 +184,6 @@ functions:
           export WORKDIR=${workdir}
           export BINDIR=$WORKDIR/bin ; mkdir -p $BINDIR
           export PATH=$BINDIR:$PATH
-
-          # AWS creds
-          export AWS_ACCESS_KEY_ID=${mms_eng_test_aws_access_key}
-          export AWS_SECRET_ACCESS_KEY=${mms_eng_test_aws_secret}
-          export AWS_REGION=${mms_eng_test_aws_region}
-          export AWS_DEFAULT_REGION=${mms_eng_test_aws_region}
-          export KOPS_STATE_STORE=s3://kube-om-state-store
-
-          if [ ! -z ${cluster_name} ]; then
-             export CLUSTER=${cluster_name}
-           else
-             export CLUSTER=e2e.mongokubernetes.com
-          fi
-
-          echo "Downloading kops"
-          curl -s -L https://github.com/kubernetes/kops/releases/download/1.11.1/kops-linux-amd64 -o kops
-          chmod +x kops
-          mv kops $BINDIR
-
-          if ! kops get clusters | grep -q $CLUSTER; then
-            echo "Cluster $CLUSTER not found, exiting..."
-            echo "run \"make recreate-e2e-kops imsure=yes cluster=$CLUSTER\""
-            kops get clusters
-            exit 1
-          fi
-
-          kops export kubecfg $CLUSTER
 
           echo "Downloading kubectl"
           curl -s -LO https://storage.googleapis.com/kubernetes-release/release/v1.11.3/bin/linux/amd64/kubectl
@@ -216,8 +197,18 @@ functions:
           mv linux-amd64/helm $BINDIR
           rm $HELM
 
-          if echo "${build_variant}" | grep -q "openshift"; then
-            echo "Downloading OC"
+
+  setup_kubernetes_environment:
+  - command: shell.exec
+    params:
+      shell: bash
+      script: |
+          export WORKDIR=${workdir}
+          export BINDIR=$WORKDIR/bin
+          export PATH=$BINDIR:$PATH
+
+          if [ "${kube_environment_name}" = "openshift_3_11" ]; then
+            echo "Downloading OC & setting up Openshift cluster"
             OC_PKG=oc-linux.tar.gz
             curl -s -L https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz --output $OC_PKG
             tar xfz $OC_PKG &> /dev/null
@@ -227,6 +218,37 @@ functions:
             echo "Token: ${openshift_cluster_token}"
             oc login ${openshift_cluster_url} --token=${openshift_cluster_token} --insecure-skip-tls-verify
             kubectl config use-context default/master-openshift-cluster-mongokubernetes-com:8443/admin
+          elif [ "${kube_environment_name}" = "vanilla_1_11" ]; then
+            if [ ! -z ${cluster_name} ]; then
+              export CLUSTER=${cluster_name}
+            else
+              export CLUSTER=e2e.mongokubernetes.com
+            fi
+
+            # AWS creds
+            export AWS_ACCESS_KEY_ID=${mms_eng_test_aws_access_key}
+            export AWS_SECRET_ACCESS_KEY=${mms_eng_test_aws_secret}
+            export AWS_REGION=${mms_eng_test_aws_region}
+            export AWS_DEFAULT_REGION=${mms_eng_test_aws_region}
+            export KOPS_STATE_STORE=s3://kube-om-state-store
+
+            echo "Downloading kops"
+            curl -s -L https://github.com/kubernetes/kops/releases/download/1.11.1/kops-linux-amd64 -o kops
+            chmod +x kops
+            mv kops $BINDIR
+
+            if ! kops get clusters | grep -q $CLUSTER; then
+              echo "Cluster $CLUSTER not found, exiting..."
+              echo run "make recreate-e2e-kops imsure=yes cluster=$CLUSTER"
+              kops get clusters
+              exit 1
+            fi
+
+            kops export kubecfg $CLUSTER
+
+          else
+            echo "kube_environment_name not recognized"
+            echo "value is <<${kube_environment_name}>>. If empty it means it was not set"
           fi
 
 
@@ -567,22 +589,40 @@ tasks:
         env: development
         image_name: mongodb-enterprise-tests
         tag_images_with_version: "true"
-    - func: setup_kubectl
 
-- name: prepare_cluster
+- name: prepare_cluster_openshift_3_11
   exec_timeout_secs: 1200
   priority: 1
   commands:
     - func: clone
     - func: setup_aws
-    - func: setup_kubectl
+    - func: download_kubectl
+    - func: setup_kubernetes_environment
+      vars:
+        kube_environment_name: openshift_3_11
     - func: setup_jq
     - func: prepare_test_env
       vars:
-        <<: *ops_manager_40_first
+        <<: *ops_manager_42_current
+
+- name: prepare_cluster_vanilla_1_11
+  exec_timeout_secs: 1200
+  priority: 1
+  commands:
+    - func: clone
+    - func: setup_aws
+    - func: setup_jq
+    - func: download_kubectl
+    - func: setup_kubernetes_environment
+      vars:
+        kube_environment_name: vanilla_1_11
     - func: prepare_test_env
       vars:
-        <<: *ops_manager_40_current
+        <<: *ops_manager_40_first
+
+    - func: prepare_test_env
+      vars:
+        <<: *ops_manager_42_current
 
 - name: e2e_operator_upgrade
   exec_timeout_secs: 1200
@@ -823,8 +863,10 @@ task_groups:
 - name: e2e_core_task_group
   max_hosts: 3
   setup_group:
-    - func: "clone"
-    - func: "setup_kubectl"
+    - func: clone
+    - func: download_kubectl
+    - func: setup_kubernetes_environment
+
   tasks:
     - e2e_all_mongodb_resources_parallel
     - e2e_standalone_config_map
@@ -857,8 +899,10 @@ task_groups:
 - name: e2e_tls_task_group
   max_hosts: 3
   setup_group:
-    - func: "clone"
-    - func: "setup_kubectl"
+    - func: clone
+    - func: download_kubectl
+    - func: setup_kubernetes_environment
+
   tasks:
     - e2e_sharded_cluster_tls_require
     - e2e_standalone_no_tls_no_status_is_set
@@ -871,10 +915,11 @@ task_groups:
     - func: "upload_e2e_logs"
 
 - name: e2e_tls_custom_ca_task_group
-  max_hosts: 3
   setup_group:
-    - func: "clone"
-    - func: "setup_kubectl"
+    - func: clone
+    - func: download_kubectl
+    - func: setup_kubernetes_environment
+
   tasks:
     - e2e_replica_set_tls_require_custom_ca
     - e2e_sharded_cluster_tls_require_custom_ca
@@ -885,8 +930,10 @@ task_groups:
 - name: e2e_core_others_task_group
   max_hosts: 1
   setup_group:
-    - func: "clone"
-    - func: "setup_kubectl"
+    - func: clone
+    - func: download_kubectl
+    - func: setup_kubernetes_environment
+
   tasks:
     - e2e_sharded_cluster_scale_shards
   teardown_task:
@@ -895,8 +942,9 @@ task_groups:
 - name: e2e_x509_task_group
   max_hosts: 1
   setup_group:
-    - func: "clone"
-    - func: "setup_kubectl"
+    - func: clone
+    - func: download_kubectl
+    - func: setup_kubernetes_environment
   tasks:
     - e2e_tls_x509_rs
     - e2e_tls_x509_sc
@@ -911,8 +959,9 @@ task_groups:
 - name: e2e_multiple_namespace_task_group
   max_hosts: 100
   setup_group:
-    - func: "clone"
-    - func: "setup_kubectl"
+    - func: clone
+    - func: download_kubectl
+    - func: setup_kubernetes_environment
   tasks:
     - e2e_replica_set_different_namespaces
   teardown_task:
@@ -942,13 +991,14 @@ buildvariants:
   depends_on:
     - name: build_images
       variant: init_test_run
-    - name: prepare_cluster
+    - name: prepare_cluster_vanilla_1_11
       variant: init_test_run
   run_on:
   - archlinux-test
   stepback: false
   expansions:
     <<: *ops_manager_40_first
+    kube_environment_name: vanilla_1_11
   tasks:
   - name: "e2e_core_task_group"
   - name: "e2e_tls_task_group"
@@ -958,13 +1008,14 @@ buildvariants:
   depends_on:
     - name: build_images
       variant: init_test_run
-    - name: prepare_cluster
+    - name: prepare_cluster_vanilla_1_11
       variant: init_test_run
   run_on:
   - archlinux-test
   stepback: false
   expansions:
-    <<: *ops_manager_40_current
+    <<: *ops_manager_42_current
+    kube_environment_name: vanilla_1_11
   tasks:
   - name: "e2e_tls_task_group"
   - name: "e2e_x509_task_group"
@@ -975,13 +1026,14 @@ buildvariants:
   depends_on:
     - name: build_images
       variant: init_test_run
-    - name: prepare_cluster
+    - name: prepare_cluster_openshift_3_11
       variant: init_test_run
   run_on:
   - archlinux-test
   stepback: false
   expansions:
-    <<: *ops_manager_40_current
+    <<: *ops_manager_42_current
+    kube_environment_name: openshift_3_11
   tasks:
   - name: "e2e_core_task_group"
   - name: "e2e_tls_task_group"
@@ -999,6 +1051,7 @@ buildvariants:
   stepback: false
   expansions:
     <<: *cloud_manager_qa
+    kube_environment_name: openshift_3_11
   tasks:
   - name: "e2e_core_task_group"
   - name: "e2e_tls_task_group"
@@ -1019,6 +1072,7 @@ buildvariants:
     <<: *cloud_manager_qa
     static_namespace: "multiple-namespace-test"
     cluster_name: "e2e.multinamespace.mongokubernetes.com"
+    kube_environment_name: vanilla_1_11
   tasks:
     - name: "e2e_multiple_namespace_task_group"
 
@@ -1029,7 +1083,8 @@ buildvariants:
   stepback: false
   tasks:
   - name: build_images
-  - name: prepare_cluster
+  - name: prepare_cluster_openshift_3_11
+  - name: prepare_cluster_vanilla_1_11
 
 #
 # TODO(rodrigo): There's no mechanism that I know of to avoid running this
