CLOUDP-33147: Openshift Cluster Installation (#117)

diff --git a/.evergreen.yml b/.evergreen.yml
--- a/.evergreen.yml
+++ b/.evergreen.yml
@@ -87,6 +87,13 @@ functions:
           mv linux-amd64/helm $BINDIR
           rm $HELM
 
+          echo "Downloading OC"
+          OC_PKG=oc-linux.tar.gz
+          curl -L https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz --output $OC_PKG
+          tar xfz $OC_PKG
+          mv openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc $BINDIR
+
+
   "gotest_parse_files":
     - command: gotest.parse_files
       params:
@@ -201,8 +208,20 @@ functions:
           export WORKDIR=${workdir}
           export IS_EVERGREEN=${revision}
           export REVISION=$(git rev-parse HEAD)
-
           export PATH=${workdir}/bin:$PATH
+          export MANAGED_SECURITY_CONTEXT="false"
+
+          echo "Build Variant: ${build_variant}"
+          set -e # fail on first failed test
+
+          if [ "${build_variant}" = "e2e_kube_vanilla_v1.10" ]; then
+            echo "Nothing to setup for this variant"
+          elif [ "${build_variant}" = "e2e_openshift_origin_v3.11" ]; then
+            echo "Setting up OpenShift variant"
+            oc login ${openshift_cluster_url} --token=${openshift_cluster_token} --insecure-skip-tls-verify
+            kubectl config use-context default/master-openshift-cluster-mongokubernetes-com:8443/admin
+            export MANAGED_SECURITY_CONTEXT="true"
+          fi
 
           # A complete environment is set each time.
           TEST_STAGE=replica_set_base ./e2e_tests.sh
@@ -237,7 +256,7 @@ tasks:
     - func: "gotest_parse_files"
 
 - name: e2e_tests
-  tags: ["test", "e2e"]
+  tags: ["e2e"]
   commands:
     - func: "clone"
     - func: "check_evergreen_health"
@@ -345,3 +364,19 @@ buildvariants:
   stepback: false
   tasks:
     - ".build_and_push_images_development"
+
+- name: e2e_kube_vanilla_v1.10
+  run_on:
+  - archlinux-test
+  batchtime: 1440
+  setpback: false
+  tasks:
+  - ".e2e"
+
+- name: e2e_openshift_origin_v3.11
+  run_on:
+  - archlinux-test
+  batchtime: 1440
+  setpback: false
+  tasks:
+  - ".e2e"
