CLOUDP-38156:  Run e2e namespace tests in a different cluster (#282)

diff --git a/.evergreen.yml b/.evergreen.yml
--- a/.evergreen.yml
+++ b/.evergreen.yml
@@ -150,12 +150,25 @@ functions:
           export AWS_REGION=${mms_eng_test_aws_region}
           export AWS_DEFAULT_REGION=${mms_eng_test_aws_region}
           export KOPS_STATE_STORE=s3://kube-om-state-store
-          export CLUSTER=e2e.mongokubernetes.com
+
+          if [ ! -z ${cluster_name} ]; then
+             export CLUSTER=${cluster_name}
+           else
+             export CLUSTER=e2e.mongokubernetes.com
+          fi
 
           echo "Downloading kops"
           curl -s -L https://github.com/kubernetes/kops/releases/download/1.11.1/kops-linux-amd64 -o kops
           chmod +x kops
           mv kops $BINDIR
+
+          if ! kops get clusters | grep -q $CLUSTER; then
+            echo "Cluster $CLUSTER not found, exiting..."
+            echo "run \"make recreate-e2e-kops imsure=yes cluster=$CLUSTER\""
+            kops get clusters
+            exit 1
+          fi
+
           kops export kubecfg $CLUSTER
 
           echo "Downloading kubectl"
@@ -314,7 +327,7 @@ functions:
       shell: bash
       script: |
         echo "Configuring Cloud Manager QA"
-        if [ "${build_variant}" = "e2e_openshift_cloud_qa" ]; then
+        if echo "${build_variant}" | grep -q "cloud_qa"; then
           echo "export OM_BASE_URL=${e2e_cloud_qa_baseurl}"      > ${workdir}/.ops-manager-env
           echo "export OM_USER=${e2e_cloud_qa_user}"            >> ${workdir}/.ops-manager-env
           echo "export OM_API_KEY=${e2e_cloud_qa_apikey}"       >> ${workdir}/.ops-manager-env
@@ -356,7 +369,7 @@ functions:
           test -f ${workdir}/.ops-manager-env && source ${workdir}/.ops-manager-env
 
           # A complete environment is set each time.
-          WATCH_NAMESPACE=${watch_namespace} TASK_NAME=${task_name} ./scripts/evergreen/e2e_tests.sh
+          WATCH_NAMESPACE=${watch_namespace} TASK_NAME=${task_name} STATIC_NAMESPACE=${static_namespace} ./scripts/evergreen/e2e_tests.sh
 
   "prepare_test_env":
     - *omkp_setup
@@ -373,8 +386,11 @@ functions:
 
           # Externally managed Ops/Cloud Manager instance get configured here
           test -f ${workdir}/.ops-manager-env && source ${workdir}/.ops-manager-env
-
-          echo "Preparing Ops/Cloud Manager Version: ${ops_manager_version} in namespace ${ops_manager_namespace} on node port ${node_port}"
+          if [ $ops_manager_version = "cloud_qa" ]; then
+            echo "Preparing Cloud Manager"
+          else
+            echo "Preparing Ops Manager Version: ${ops_manager_version} in namespace ${ops_manager_namespace} on node port ${node_port}"
+          fi
           ./prepare_test_env ${ops_manager_namespace} ${ops_manager_version} ${node_port}
 
   "post_task":
@@ -391,6 +407,7 @@ functions:
 
         echo "Are there any remaining Docker images in this host?"
         docker images
+
 
 post:
    - func: "post_task"
@@ -515,16 +532,12 @@ tasks:
   commands:
     - func: "e2e_test"
 
-# Removing this test as it creates a cluster wide operator
-# that collides with every other operator running in the
-# cluster, breaking havoc
-# - name: e2e_replica_set_different_namespaces
-#   exec_timeout_secs: 600 # 10 minutes max
-#   commands:
-#     - func: "e2e_test"
-#       vars:
-#         test_name: replica_set_different_namespaces
-#         watch_namespace: "*"
+- name: e2e_replica_set_different_namespaces
+  exec_timeout_secs: 1200
+  commands:
+    - func: "e2e_test"
+      vars:
+        watch_namespace: "*"
 
 - name: e2e_standalone_config_map
   exec_timeout_secs: 600
@@ -550,13 +563,6 @@ tasks:
   exec_timeout_secs: 600
   commands:
     - func: "e2e_test"
-
-# - name: e2e_replica_set
-#   exec_timeout_secs: 600 # 10 minutes max
-#   commands:
-#     - func: "e2e_test"
-#       vars:
-#         test_name: replica_set
 
 - name: e2e_replica_set_recovery
   exec_timeout_secs: 600
@@ -732,7 +738,6 @@ task_groups:
     - e2e_replica_set_schema_validation
     - e2e_replica_set_upgrade_downgrade
     - e2e_replica_set_8_members
-    # - e2e_replica_set_different_namespaces
     - e2e_sharded_cluster
     - e2e_sharded_cluster_pv
     - e2e_sharded_cluster_recovery
@@ -777,6 +782,16 @@ task_groups:
     - e2e_tls_x509_sc
     - e2e_tls_x509_user_connectivity
     - e2e_users_schema_validation
+  teardown_task:
+    - func: "upload_e2e_artifacts"
+
+- name: e2e_multiple_namespace_task_group
+  max_hosts: 100
+  setup_group:
+    - func: "clone"
+    - func: "setup_kubectl"
+  tasks:
+    - e2e_replica_set_different_namespaces
   teardown_task:
     - func: "upload_e2e_artifacts"
 
@@ -839,6 +854,7 @@ buildvariants:
     depends_on:
       - name: setup_e2e
 
+
 - name: e2e_openshift_origin_v3.11_om_40_current
   display_name: "e2e_openshift_origin_v3.11_om_40_current"
   run_on:
@@ -879,6 +895,23 @@ buildvariants:
   - name: "e2e_x509_task_group"
     depends_on:
       - name: setup_e2e
+
+# any subsequent tasks being executed in this build variant should depend upon the previously
+# executed task in order to prevent interference
+- name: e2e_cloud_qa_clusterwide_operator
+  display_name: "e2e_cloud_qa_clusterwide_operator"
+  run_on:
+    - archlinux-test
+  stepback: false
+  expansions:
+    <<: *cloud_manager_qa
+    static_namespace: "multiple-namespace-test"
+    cluster_name: "e2e.multinamespace.mongokubernetes.com"
+  tasks:
+    - name: "setup_e2e"
+    - name: "e2e_multiple_namespace_task_group"
+      depends_on:
+        - name: setup_e2e
 
 - name: go_unit_tests
   display_name: "go_unit_tests"
