CLOUDP-37163: Epic KubeSSL (#227)
* CLOUDP-38483: Certs are created and mounted in Pods.

* CLOUDP-38486: Add SSL to automation config (#222)

* CLOUDP-37997: E2E tests SSL Replica Set (#228)

* CLOUDP-37998: E2E TLS sharded clusters (#230)

* CLOUDP-38002: Upgrade to TLS deployment from non tls (#233)

* CLOUDP:39500 ssl fixes for OM communication (#235)

* CLOUDP-39501: Support connections to ssl mms (#236)

* CLOUDP-40352: Adds strict e2e tests for SSL scaling up & down. (#239)

* CLOUDP-39719: Change TLS Custom Resource Schema (#240)

* CLOUDP-40599: Uses RSA 4096 instead of EC for Private Keys. (#242)

diff --git a/scripts/dev/deploy_operator b/scripts/dev/deploy_operator
--- a/scripts/dev/deploy_operator
+++ b/scripts/dev/deploy_operator
@@ -11,8 +11,16 @@ title "Deploying the Operator to Kubernetes cluster..."
 # checking the status of k8s cluster
 if [[ ${CLUSTER_TYPE} = "minikube" ]]; then
     ensure_minikube
-elif [[ ${CLUSTER_TYPE} = "kops" && $(kops validate cluster "${CLUSTER_NAME}" | grep -q "not found") ]]; then
-    fatal "kops cluster is not running, call \"make\" to create it"
+elif [[ ${CLUSTER_TYPE} = "kops" ]]; then
+    if kops validate cluster "${CLUSTER_NAME}" | grep -q "not found"; then
+        fatal "kops cluster is not running, call \"make\" to create it"
+    fi
+elif [[ ${CLUSTER_TYPE} = "openshift" ]]; then
+    if ! oc get nodes &> /dev/null; then
+        fatal "Could not communicate to Openshift cluster"
+    fi
+else
+    fatal "CLUSTER_TYPE=${CLUSTER_TYPE} not recognized"
 fi
 
 # making sure the namespace is created
@@ -23,4 +31,7 @@ if [[ ${REPO_TYPE} = "local" ]]; then
     pull_policy="Never"
 fi
 
-redeploy_operator "${REPO_URL}" "${OPERATOR_VERSION:-}" "${NAMESPACE:-mongodb}" "${watch_namespace:-$NAMESPACE}" "${pull_policy:-}"
+if [[ ${CLUSTER_TYPE} = "openshift" ]]; then
+    managed_security_context="true"
+fi
+redeploy_operator "${REPO_URL}" "${OPERATOR_VERSION:-}" "${NAMESPACE:-mongodb}" "${watch_namespace:-$NAMESPACE}" "${pull_policy:-}" "${managed_security_context:-}"
