Removal of unecessary cd (#886)

diff --git a/scripts/dev/print_contexts b/scripts/dev/print_contexts
--- a/scripts/dev/print_contexts
+++ b/scripts/dev/print_contexts
@@ -1,19 +1,16 @@
 #!/usr/bin/env bash
-
-set -euo pipefail
-
-cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"
+set -Eeou pipefail
 
 source scripts/funcs/errors
 
 if [[ ! -d $HOME/.operator-dev/contexts ]]; then
-    fatal "Contexts directory \"~/.operator-dev/contexts\" not found! You must init development environment using \"make init\" first"
+	fatal "Contexts directory \"~/.operator-dev/contexts\" not found! You must init development environment using \"make init\" first"
 fi
 
-for f in $HOME/.operator-dev/contexts/*; do
+for f in "$HOME"/.operator-dev/contexts/*; do
 	echo "----------"
-	echo $(basename "$f")
+	basename "$f"
 	echo "----------"
-	cat $f | grep -v "^# "
+	grep -v "^# " "$f"
 	echo
 done
