Work with different repo types (#785)

diff --git a/scripts/dev/read_context b/scripts/dev/read_context
--- a/scripts/dev/read_context
+++ b/scripts/dev/read_context
@@ -4,11 +4,15 @@ set -euo pipefail
 
 source ./scripts/dev/set_env_context
 
-# The convention: the cluster name must match the name of kubectl context
-# We expect this not to be true if kubernetes cluster is still to be created (minikube/kops)
-kubectl config use-context ${CLUSTER_NAME} || echo "Warning: failed to switch kubectl context to \"${CLUSTER_NAME}\" - does the matching Kubernetes cluster exist?"
+if [ -z "${CLUSTER_NAME-}" ]; then
+    echo "Skipping setting cluster_name"
+else
+    # The convention: the cluster name must match the name of kubectl context
+    # We expect this not to be true if kubernetes cluster is still to be created (minikube/kops)
+    kubectl config use-context ${CLUSTER_NAME} || echo "Warning: failed to switch kubectl context to \"${CLUSTER_NAME}\" - does the matching Kubernetes cluster exist?"
 
-# Setting the default namespace for current context
-kubectl config set-context "$(kubectl config current-context)" --namespace=${NAMESPACE} &>/dev/null || true
+    # Setting the default namespace for current context
+    kubectl config set-context "$(kubectl config current-context)" --namespace=${NAMESPACE} &>/dev/null || true
 
-echo "Current context: ${CURRENT_CONTEXT} (kubectl context: ${CLUSTER_NAME})"
+    echo "Current context: ${CURRENT_CONTEXT} (kubectl context: ${CLUSTER_NAME})"
+fi
