CLOUDP-31604: fix for permissions for cloud persistent storages (#82)

diff --git a/scripts/build/build_operator b/scripts/build/build_operator
--- a/scripts/build/build_operator
+++ b/scripts/build/build_operator
@@ -3,6 +3,13 @@
 # A script for both devs and Evergreen to compile the Operator
 # Any dev or evergreen specifics should go into the dev or evergreen scripts folders
 #
+
+failfast=$1
+
+if [ -z "${failfast}" ]; then
+    failfast=1
+fi
+
 set -xeuo pipefail
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -23,14 +30,17 @@ go version
 ## Unit Test (note, that we combine testing and compiling in one file as they need the same
 # preliminary actions (dep, codegen)). Local tests using real OM are excluded
 # TODO remove the exclusion for 'util' in CLOUDP-31476
-go test -v  $(go list ./... | grep -v '/\(pkg\|local\|util\)') | tee "${GOPATH}/ops-manager-kubernetes.suite"
+go test -v  $(go list ./... | grep -v '/\(pkg\|local\|util\)') | tee "${GOPATH}/ops-manager-kubernetes.suite" || echo "Some tests failed!"
 
 if grep "FAIL" "${GOPATH}/ops-manager-kubernetes.suite" ; then
-    echo "Some tests failed!"
-    exit 1
+    # In some cases we don't need to exit the program (if we want to parse test results later)
+    if [ $failfast -eq 1 ]; then
+        echo "Exiting program"
+        exit 1
+    fi
+else
+    ## Compile!
+    CGO_ENABLED=0 GOOS=linux go build -o docker/mongodb-enterprise-operator/content/mongodb-enterprise-operator
+
+    echo "The Operator was built successfully"
 fi
-
-## Compile!
-CGO_ENABLED=0 GOOS=linux go build -o docker/mongodb-enterprise-operator/content/mongodb-enterprise-operator
-
-echo "The Operator was built successfully"
