Dev script improvements to support multiple base images (#396)

diff --git a/scripts/build/prepare_build_environment b/scripts/build/prepare_build_environment
--- a/scripts/build/prepare_build_environment
+++ b/scripts/build/prepare_build_environment
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"
+
 # Only installs 'dep' if not already installed
 if [ ! "$(which dep)" ]; then
     mkdir -p "${GOBIN}"
@@ -9,6 +11,6 @@ fi
 dep ensure -v
 
 ## Generate code
-./scripts/build/codegen.sh
+scripts/build/codegen.sh
 
 go version
